apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Prometheus2677/k8s-ingress-demo
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastapi-demo
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/fastapi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-demo
  targetNamespace: default
